version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  shortcreator_fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - video_folder:/video_folder

volumes:
  db:
  video_folder:
 
  

  

    